<html xmlns:concordion="http://www.concordion.org/2007/concordion">
<head>
    <title>Overview</title>
    <link href="../../../style.css" rel="stylesheet" type="text/css"/>
    <style>
        p.success {
            padding: 2px;
        }

        .success, .success * {
            background-color: #afa !important;
        }

        .success pre {
            background-color: #bbffbb;
        }

        .failure, .failure * {
            background-color: #ffb0b0;
            padding: 1px;
        }

        .special {
            font-style: italic;
        }        
    </style>
</head>
<body>
<h1>Concordion Ant Task User Manual</h1>

<p>
    The Concordion Ant Task will
    <ul>
        <li>generate a single Html page collecting all your <a href="http://www.concordion.org">Concordion</a> specifications in one place</li>
        <li>annotate this overview page with Concordion's <code>run</code> command (run your specifications as a <i>suite</i>)</li>
        <li>slot into your existing build process</li>
        <li>allow you to customise the generated overview Html page</li>
    </ul> 
</p>
<p>
    For example, these pages were generated by Concordion executing this overview page generated by the Ant task. 
</p>

<#assign counter = 0>
<#assign ignored = 0>
<div id="tests">
<#list tests?keys as group>
<h2>${group}</h2>
<ul>
<#list tests[group] as test>
<#assign counter = counter + 1>
<#if test.ignore || test.duplicate>
    <#assign ignored = ignored + 1>
    <li>
        <a class="ignored" href="${test.locationAsRelativeUrl}">${test.title}</a>
    </li>
<#else>
    <li>
        <a concordion:run="concordion" href="${test.locationAsRelativeUrl}">${test.title}</a>
    </li>
</#if>
</#list>
</ul>
</#list>
</div>

<p class="idea">${counter} tests, ${ignored} ignored or duplicate</p>
</body>
</html>